import { ThemeProvider } from '@/components/theme-provider'
import Header from '@/components/ui/header'
import { Architects_Daughter, Atkinson_Hyperlegible, Inter } from 'next/font/google'
import type { Metadata } from 'next'

import './css/style.css'

const inter = Atkinson_Hyperlegible({
    subsets: ['latin'],
    variable: '--font-inter',
    weight: '400',
    display: 'swap',
})

const architects_daughter = Architects_Daughter({
    subsets: ['latin'],
    variable: '--font-architects-daughter',
    weight: '400',
    display: 'swap',
})

// const atkinson_hyperlegible = Atkinson_Hyperlegible({
//     subsets: ['latin'],
//     variable: '--font-atkinson-hyperlegible',
//     weight: '400',
//     display: 'swap',
// })

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <body
                className={`${inter.variable} ${architects_daughter.variable} font-inter antialiased bg-background text-foreground`}
            >
                <ThemeProvider
                    attribute="class"
                    defaultTheme="dark"
                    enableSystem
                    disableTransitionOnChange
                >
                    <div className="flex flex-col min-h-screen overflow-hidden">
                        <Header />
                        {children}
                    </div>
                </ThemeProvider>
            </body>
        </html>
    )
}
